export default function Home() {
  return <main className="site">
    <header className="site-nav"><a className="site-brand" href="/"><i>F</i>flowstate</a><nav><a href="#product">Product</a><a href="#principles">Principles</a><a href="#team">Team</a></nav><a className="nav-cta" href="/desk">Open recovery desk</a></header>
    <section className="pitch-hero">
      <div className="pitch-copy"><p className="eyebrow">Payment recovery, made accountable</p><h1>When a payment route breaks, your team knows what to do next.</h1><p>Flowstate detects a payment failure, proposes a controlled response, and shows the evidence after the change. No black box. No invented outcomes.</p><div className="pitch-actions"><a className="solid-button" href="/desk">See the live desk <span>→</span></a><a className="text-link" href="#product">How it works</a></div></div>
      <div className="flo-stage"><div className="flo-note"><strong>Meet Flo</strong><span>Keeps the team oriented when a route needs attention.</span></div><img src="/flo.png" alt="Flo, the Flowstate payment recovery guide" /></div>
    </section>
    <section className="proof-band"><div><strong>One incident view</strong><span>See the affected route, decision, and result together.</span></div><div><strong>Controlled change</strong><span>High-impact actions wait for a named approver.</span></div><div><strong>Measured outcome</strong><span>Treatment is compared with concurrent control traffic.</span></div></section>
    <section className="story-section" id="product"><div className="section-marker">01 / The problem</div><div><p className="eyebrow">Payment operations</p><h2>A failing route creates a fast decision, not a reporting exercise.</h2><p>Teams need the route, the reason it is failing, the action within policy, and the evidence that it helped. Flowstate keeps all four in one reviewable record.</p></div></section>
    <section className="flow-section" id="principles"><p className="eyebrow">A clear operating loop</p><div className="flow-steps"><article><span>01</span><h3>Find the break</h3><p>Watch payment success, latency, and retry patterns across issuers and routes.</p></article><article><span>02</span><h3>Choose a safe response</h3><p>Apply policy limits before a change reaches customer traffic.</p></article><article><span>03</span><h3>Prove the result</h3><p>Keep a control group so recovery is measured, not assumed.</p></article></div></section>
    <section className="team-section" id="team"><div><p className="eyebrow">For the people on call</p><h2>Flo explains where the team is in the recovery, without getting in the way.</h2><p>Flo is a guide, not a decision-maker. The desk always shows the route, the policy, and the named approval behind every important change.</p><a className="text-link" href="/desk">Open the desk</a></div><img src="/flo.png" alt="Flo holding a payment recovery checklist" /></section>
    <footer className="site-footer"><a className="site-brand" href="/"><i>F</i>flowstate</a><span>Payment recovery with a clear record.</span><a href="/desk">Recovery desk</a></footer>
  </main>;
}
